version: "3.8"

services:
  notifier:
    container_name: clean-arch-notifier
    build:
      context: .
      dockerfile: notifier/Dockerfile
    image: clean-arch-notifier
    restart: always
    environment:
      - ENVIRONMENT=Stag
    depends_on:
      - rabbitmq
    networks:
      - clean-arch-network

  golang-mongo:
    container_name: clean-arch-mongodb
    image: mongo:latest
    restart: on-failure
    volumes:
      - ./.docker/data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    networks:
      - clean-arch-network

  rabbitmq:
    container_name: clean-arch-broker
    image: rabbitmq:3.9-alpine
    restart: on-failure
#    volumes:
#      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
#      - ./.docker/rabbitmq/log/:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - clean-arch-network

networks:
  clean-arch-network:
    driver: bridge
