version: '3.5'

services:
  clean-app:
    container_name: clean-app
    build: .
    restart: on-failure
    volumes:
      - .:/usr/src/app
    depends_on:
      - clean-mongo
    networks:
      clean-arch
  clean-mongo:
    container_name: clean-mongo
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo