version: "3.3"

services:

  # Create services with RabbitMQ.
  message-broker:
    image: rabbitmq:3.9-alpine
    container_name: broker
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
#    volumes:
#      - ${HOME}/dev-rabbitmq/data/:/var/lib/rabbitmq
#      - ${HOME}/dev-rabbitmq/log/:/var/log/rabbitmq
    restart: always
    networks:
      - dev-network

networks:
  # Create a new Docker network.
  dev-network:
    driver: bridge